branches:
  only:
    - master
    - /^v.*$/
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TEST_DATABASE_URL=postgresql://postgres@localhost:5432/pytest_test
addons:
  postgresql: "9.6"
install:
  - pip install --upgrade pip
  - pip install -U -r requirements/main.txt -r requirements/tests.txt
  - pip install -e .
script: pytest
